sudo: required
services:
  - docker

before_install:
  - docker build -t gianlucamori/frontend-docker -f Dockerfile.dev .

script:
  - docker run -it gianlucamori/frontend-docker npm run test -- --watchAll=false

deploy:
  provider: elastickbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket-name: "elasticbeanstalk-eu-west-2-009429312724"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
