sudo: required
services:
  - docker

before_install:
  - docker build -t gianlucamori/frontend-docker -f Dockerfile.dev .

script:
  - docker run -it gianlucamori/frontend-docker npm run test -- --watchAll=false
